spring:
  application:
    name: fortunelink
  config:
    import: optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
    ddl-auto: validate # Good for testing - recreates schema each run, change to validate when using flyway
    show-sql: true           # Helpful to see generated SQL during development
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true     # Makes SQL output readable

  # Enable H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false # doesn't suuport latest 17 postgres
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.boot.context.config: DEBUG